networks:
  homegear:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-homegear
    enable_ipv6: true
    ipam:
      config:
      - subnet: 172.17.0.0/24
      - subnet: 2002:b0c6:d4db:0:17::/80
      driver: default
    name: homegear
services:
  homegear:
    container_name: homegear
    depends_on:
      mosquitto:
        condition: service_started
    devices:
    - /dev/ttyAMA0:/dev/ttyAMA0
    - /dev/ttyACM0:/dev/ttyACM0
    environment:
      HOST_USER_GID: '1000'
      HOST_USER_ID: '1000'
      TZ: Europe/Berlin
    hostname: homegear
    image: homegear/homegear:testing
    labels:
      docker.group: homegear
    networks:
      homegear: null
    ports:
    - protocol: tcp
      published: 2001
      target: 2001
    - protocol: tcp
      published: 2002
      target: 2002
    - protocol: tcp
      published: 2003
      target: 2003
    restart: unless-stopped
    stop_grace_period: 60s
    volumes:
    - /docker/homegear/etc:/etc/homegear:Z
    - /docker/homegear/lib:/var/lib/homegear:Z
    - /docker/homegear/log:/var/log/homegear:Z
    - /sys:/sys:rw
  mosquitto:
    build:
      context: /home/pi/docker-compose-mosquitto
      dockerfile: Dockerfile
    container_name: mosquitto
    environment:
      TZ: Europe/Berlin
    hostname: mosquitto
    image: mosquitto:latest
#    image: eclipse-mosquitto:latest
    labels:
      docker.group: homegear
    networks:
      homegear: null
    ports:
    - protocol: tcp
      published: 1883
      target: 1883
    - protocol: tcp
      published: 8883
      target: 8883
    restart: unless-stopped
    volumes:
    - /docker/mosquitto/config:/mosquitto/config:rw
    - /docker/mosquitto/data:/mosquitto/data:rw
    - /docker/mosquitto/log:/mosquitto/log:rw
version: '3.8'

