networks:
  monitor:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-monitor
    enable_ipv6: true
    ipam:
      config:
      - subnet: 172.18.0.0/24
      - subnet: 2002:b0c6:d4db:0:18::/80
      driver: default
    name: monitor
services:
  chronograf:
    command: --influxdb-url=http://influxdb:8086
    container_name: chronograf
    depends_on:
      influxdb:
        condition: service_started
    environment:
      TZ: Europe/Berlin
    hostname: chronograf
    image: chronograf:latest
    labels:
      docker.group: monitor
    networks:
      monitor: null
    ports:
    - protocol: tcp
      published: 8888
      target: 8888
    restart: unless-stopped
    volumes:
    - /docker/chronograf/lib:/var/lib/chronograf:rw
  collectd:
    container_name: collectd
    depends_on:
      influxdb:
        condition: service_started
    environment:
      TZ: Europe/Berlin
    hostname: collectd
    image: jipp13/fritzcollectd:latest
    labels:
      docker.group: monitor
    networks:
      monitor: null
    restart: unless-stopped
    volumes:
    - /docker/collectd/etc:/etc/collectd:ro
  grafana:
    container_name: grafana
    depends_on:
      influxdb:
        condition: service_started
    environment:
      TZ: Europe/Berlin
    hostname: grafana
    image: grafana/grafana:latest
    networks:
      monitor: null
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: unless-stopped
    volumes:
    - grafana-storage:/var/lib/grafana:rw
  influxdb:
    container_name: influxdb
    environment:
      TZ: Europe/Berlin
    expose:
    - 25826/udp
    hostname: influxdb
    image: influxdb:latest
    labels:
      docker.group: monitor
    networks:
      monitor: null
    ports:
    - protocol: tcp
      published: 8086
      target: 8086
    - protocol: udp
      published: 25826
      target: 25826
    restart: unless-stopped
    volumes:
    - /docker/influxdb/etc:/etc/influxdb:rw
    - /docker/influxdb/lib:/var/lib/influxdb:rw
  telegraf:
    container_name: telegraf
    depends_on:
      influxdb:
        condition: service_started
    environment:
      HOST_PROC: /host/proc
      TZ: Europe/Berlin
    hostname: telegraf
    image: telegraf:latest
    labels:
      docker.group: monitor
    networks:
      monitor: null
    restart: unless-stopped
    volumes:
    - /docker/telegraf/etc:/etc/telegraf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc:/host/proc:rw
version: '3.8'
volumes:
  grafana-storage:
    name: grafana-storage

