networks:
  owncloud:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-owncloud
    enable_ipv6: true
    ipam:
      config:
      - subnet: 192.168.21.0/24
      - subnet: 2002:b0c6:d4db:0:21::/80
      driver: default
    name: owncloud
services:
  owncloud:
    labels:
      docker.group: owncloud
    networks:
      owncloud: null
    container_name: owncloud
    dns:
    - 192.168.178.1
    hostname: owncloud
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /docker/owncloud/data:/docker/owncloud/data

  db:
    labels:
      docker.group: owncloud
    networks:
      owncloud: null
    container_name: db
    hostname: db
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /docker/mysql/mysql:/var/lib/mysql
      - /docker/mysql/backup:/var/lib/backup

  redis:
    labels:
      docker.group: owncloud
    networks:
      owncloud: null
    container_name: redis
    hostname: redis
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /docker/redis/redis:/var/lib/redis

version: '3'

