version: '3'
services:
 mosquitto:
  image: eclipse-mosquitto
  ports:
   - "1883:1883"
   - "8883:8883"
  volumes:
   - /home/pi/docker/mosquitto/config:/mosquitto/config
   - /home/pi/docker/mosquitto/data:/mosquitto/data
   - /home/pi/docker/mosquitto/log:/mosquitto/log
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'

 influxdb:
  image: influxdb
  ports:
   - "8086:8086"
  volumes:
   - /home/pi/docker/influxdb/data:/var/lib/influxdb
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'

 telegraf:
  image: telegraf
  command: -config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
  volumes:
   - /home/pi/docker/telegraf/config:/etc/telegraf
   - /var/run/docker.sock:/var/run/docker.sock
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb
   - mosquitto

 grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  volumes:
   - /home/pi/docker/grafana/log:/var/log/grafana
   - /home/pi/docker/grafana/data:/var/lib/grafana
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb

 chronograf:
  image: chronograf
  ports:
   - "8888:8888"
  volumes:
   - /home/pi/docker/chronograf/data:/var/lib/chronograf
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb

 kapacitor:
  image: kapacitor
  ports:
   - "9092:9092"
  volumes:
   - /home/pi/docker/kapacitor/config:/etc/kapacitor
   - /home/pi/docker/kapacitor/data:/var/lib/kapacitor
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb
