version: '3'
services:
 mosquitto:
# sudo chown 1883:1883 /home/pi/docker/mosquitto/data/ /home/pi/docker/mosquitto/log/
  image: eclipse-mosquitto
  ports:
   - "1883:1883"
   - "8883:8883"
  volumes:
   - ./mosquitto/config:/mosquitto/config
   - ./mosquitto/data:/mosquitto/data
   - ./mosquitto/log:/mosquitto/log
  networks:
   - woke
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'

 influxdb:
  image: influxdb
  ports:
   - "8086:8086"
  volumes:
   - ./influxdb/data:/var/lib/influxdb
  networks:
   - woke
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'

 telegraf:
  image: telegraf
  command: -config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
  volumes:
   - ./telegraf/config:/etc/telegraf
   - /var/run/docker.sock:/var/run/docker.sock
  networks:
   - woke
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb
   - mosquitto

 chronograf:
  image: chronograf
  ports:
   - "8888:8888"
  volumes:
   - ./chronograf/data:/var/lib/chronograf
  networks:
   - woke
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb

 kapacitor:
  image: kapacitor
  ports:
   - "9092:9092"
  volumes:
   - ./kapacitor/config:/etc/kapacitor
   - ./kapacitor/data:/var/lib/kapacitor
  networks:
   - woke
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb

 grafana:
# sudo chown 472 /home/pi/docker/grafana/data/
  image: grafana/grafana
  ports:
   - "3000:3000"
  volumes:
   - ./grafana/log:/var/log/grafana
   - ./grafana/data:/var/lib/grafana
  networks:
   - woke
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: '0.50'
  depends_on:
   - influxdb

networks:
 woke:
