esphome:
  name: actor-garage
esp8266:
  board: d1_mini_pro
wifi:
  ap:
    ssid: actor-garage
    password: TJ3FEvhl31QJ
  networks:
  - ssid: wobilix
    password: Eins2Drei4
captive_portal: {}
logger:
  level: INFO
ota:
  password: 0acht15
text_sensor:
- platform: version
  name: ESPHome Version
mqtt:
  broker: lemonpi
  username: actor-garage
  password: 0acht15
web_server:
  port: 80
api:
  password: ""
sensor:
- platform: homeassistant
  name: "Actor Garage"
  entity_id: actor.garage
  attribute: gate
- platform: uptime
  name: Uptime
- platform: wifi_signal
  name: WiFi Signal
switch:
- platform: gpio
  pin:
    number: D5
  id: relay
  name: relay
  internal: true
- platform: template
  name: garage
  turn_on_action:
    then:
    - switch.turn_on:
        id: relay
    - delay: 500ms
    - switch.turn_off:
        id: relay
