esphome:
  name: sensor-power
esp8266:
  board: d1_mini_pro
wifi:
  ap:
    ssid: sensor-power
    password: ojPPqvMnbCO3
  networks:
  - ssid: wobilix
    password: Eins2Drei4
captive_portal: {}
logger:
  level: INFO
ota:
  password: 0acht15
text_sensor:
- platform: version
  name: ESPHome Version
mqtt:
  broker: lemonpi
  username: sensor-power
  password: 0acht15
web_server:
  port: 80
sensor:
- platform: uptime
  name: Uptime
- platform: wifi_signal
  name: WiFi Signal
- platform: pulse_counter
  pin:
    number: D2
  name: Power
