substitutions:
  devicename: sensor-esp32-cam
  comment: Wemos D1 Mini Pro
  name: woke.sensor-esp32-cam
  version: 1.0.0
esp32:
  board: esp32cam

<<: !include common/base.yaml

text_sensor:
- <<: !include common/text_sensor.yaml
status_led:
  pin: GPIO33
sensor:
- <<: !include common/sensor_uptime.yaml
- <<: !include common/sensor_wifi_signal.yaml
binary_sensor:
- <<: !include common/binary_sensor_status.yaml
esp32_camera:
  name: $devicename
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: XGA
  jpeg_quality: 13
#  max_framerate: 5 fps
#  idle_framerate: 0 fps
esp32_camera_web_server:
- port: 8080
  mode: stream
- port: 8081
  mode: snapshot
light:
- platform: binary
  name: "Licht"
  output: light_output
output:
- platform: gpio
  id: light_output
  pin: GPIO4
