wifi_networks_ssid: wobilix
wifi_networks_password: Eins2Drei4
wifi_ap_password: ojPPqvMnbCO3
ota_password: 0acht15!
api_encryption_key: Mcgg99TAe1vpW2OBF83s2BxXdp2RB6NQ1rwZ5ftRszQ=
web_server_username: esphome
web_server_password: 0acht15
