networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-backend
    ipam:
      config:
      - subnet: 172.16.0.0/24
      driver: default
    name: backend
services:
  homegear:
    container_name: homegear
    depends_on:
    - mosquitto
    devices:
    - /dev/ttyAMA0:/dev/ttyAMA0
    - /dev/ttyACM0:/dev/ttyACM0
    environment:
      HOST_USER_GID: '1000'
      HOST_USER_ID: '1000'
      TZ: Europe/Berlin
    hostname: homegear
    image: homegear/homegear:testing
    networks:
      backend: null
    ports:
    - protocol: tcp
      published: 2001
      target: 2001
    - protocol: tcp
      published: 2002
      target: 2002
    - protocol: tcp
      published: 2003
      target: 2003
    restart: unless-stopped
    stop_grace_period: 60s
    volumes:
    - /docker/homegear/etc:/etc/homegear:Z
    - /docker/homegear/lib:/var/lib/homegear:Z
    - /docker/homegear/log:/var/log/homegear:Z
    - /sys:/sys:rw
  homegear-testing:
    container_name: homegear-testing
    environment:
      HOST_USER_GID: '1000'
      HOST_USER_ID: '1000'
      TZ: Europe/Berlin
    hostname: homegear-testing
    image: homegear/homegear:testing
    networks:
      backend: null
    ports:
    - protocol: tcp
      published: 3001
      target: 2001
    - protocol: tcp
      published: 3002
      target: 2002
    - protocol: tcp
      published: 3003
      target: 2003
    restart: "no"
    stop_grace_period: 60s
    volumes:
    - /docker/homegear-testing/etc:/etc/homegear:Z
    - /docker/homegear-testing/lib:/var/lib/homegear:Z
    - /docker/homegear-testing/log:/var/log/homegear:Z
  mosquitto:
    container_name: mosquitto
    environment:
      TZ: Europe/Berlin
    hostname: mosquitto
    image: eclipse-mosquitto
    networks:
      backend: null
    ports:
    - protocol: tcp
      published: 1883
      target: 1883
    - protocol: tcp
      published: 8883
      target: 8883
    restart: unless-stopped
    volumes:
    - /docker/mosquitto/config:/mosquitto/config:rw
    - /docker/mosquitto/data:/mosquitto/data:rw
    - /docker/mosquitto/log:/mosquitto/log:rw
version: '3.8'
