networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-backend
    ipam:
      config:
      - subnet: 172.16.0.0/24
      driver: default
    name: backend
services:
  chronograf:
    command: --influxdb-url=http://influxdb:8086
    container_name: chronograf
    depends_on:
    - influxdb
    hostname: chronograf
    image: chronograf
    networks:
      backend:
        ipv4_address: 172.16.0.10
    ports:
    - protocol: tcp
      published: 8888
      target: 8888
    restart: unless-stopped
    volumes:
    - /docker/chronograf/lib:/var/lib/chronograf:rw
  collectd:
    container_name: collectd
    depends_on:
    - influxdb
    hostname: collectd
    image: jipp13/fritzcollectd
    networks:
      backend:
        ipv4_address: 172.16.0.12
    restart: unless-stopped
    volumes:
    - /docker/collectd/etc:/etc/collectd:ro
  grafana:
    container_name: grafana
    depends_on:
    - influxdb
    hostname: grafana
    image: grafana/grafana
    networks:
      backend:
        ipv4_address: 172.16.0.14
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: unless-stopped
    volumes:
    - grafana-storage:/var/lib/grafana:rw
  homegear:
    container_name: homegear
    devices:
    - /dev/ttyAMA0:/dev/ttyAMA0
    - /dev/ttyACM0:/dev/ttyACM0
    environment:
      HOST_USER_GID: '1000'
      HOST_USER_ID: '1000'
      TZ: Europe/Berlin
    hostname: homegear
    image: homegear/homegear
    networks:
      backend:
        ipv4_address: 172.16.0.16
    ports:
    - protocol: tcp
      published: 2001
      target: 2001
    - protocol: tcp
      published: 2002
      target: 2002
    - protocol: tcp
      published: 2003
      target: 2003
    restart: unless-stopped
    volumes:
    - /docker/homegear/etc:/etc/homegear:Z
    - /docker/homegear/lib:/var/lib/homegear:Z
    - /docker/homegear/log:/var/log/homegear:Z
    - /sys:/sys:rw
  influxdb:
    container_name: influxdb
    expose:
    - 25826/udp
    hostname: influxdb
    image: influxdb
    networks:
      backend:
        ipv4_address: 172.16.0.18
    ports:
    - protocol: tcp
      published: 8086
      target: 8086
    - protocol: udp
      published: 25826
      target: 25826
    restart: unless-stopped
    volumes:
    - /docker/influxdb/etc:/etc/influxdb:rw
    - /docker/influxdb/lib:/var/lib/influxdb:rw
  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto
    networks:
      backend:
        ipv4_address: 172.16.0.20
    ports:
    - protocol: tcp
      published: 1883
      target: 1883
    - protocol: tcp
      published: 8883
      target: 8883
    restart: unless-stopped
    volumes:
    - /docker/mosquitto/config:/mosquitto/config:rw
    - /docker/mosquitto/data:/mosquitto/data:rw
    - /docker/mosquitto/log:/mosquitto/log:rw
  telegraf:
    container_name: telegraf
    depends_on:
    - influxdb
    - mosquitto
    environment:
      HOST_PROC: /host/proc
    hostname: telegraf
    image: telegraf
    networks:
      backend:
        ipv4_address: 172.16.0.22
    restart: unless-stopped
    volumes:
    - /docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc:/host/proc:rw
version: '3.8'
volumes:
  grafana-storage:
    name: grafana-storage

